/**
 * AI Smart Hospital Management System - Frontend Configuration
 */

// Live Render Backend API URL
const BACKEND_RENDER_URL = 'https://ai-smart-hospital-backend-w26k.onrender.com/api';

const CONFIG = {
  // Automatically detects local environment vs live deployment (Vercel / Netlify / Render)
  API_BASE_URL: window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
    ? 'http://localhost:5000/api'
    : (localStorage.getItem('CUSTOM_API_URL') || BACKEND_RENDER_URL),

  SPECIALIZATIONS: [
    'General Physician',
    'Cardiologist',
    'Dermatologist',
    'Neurologist',
    'Pediatrician',
    'Orthopedic',
    'Gynecologist',
    'ENT Specialist',
    'Ophthalmologist',
    'Psychiatrist',
    'Dentist',
    'Pulmonologist',
    'Gastroenterologist',
    'Urologist'
  ],

  TAMIL_NADU_DISTRICTS: [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Salem',
    'Tiruchirappalli',
    'Tirunelveli',
    'Vellore',
    'Erode',
    'Thanjavur',
    'Dindigul',
    'Kanchipuram',
    'Chengalpattu',
    'Tiruppur',
    'Cuddalore',
    'Karur',
    'Nagapattinam',
    'Namakkal',
    'Nilgiris',
    'Pudukkottai',
    'Ramanathapuram',
    'Sivaganga',
    'Tenkasi',
    'Theni',
    'Thoothukudi',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Ranipet',
    'Tirupattur',
    'Viluppuram',
    'Virudhunagar',
    'Krishnagiri',
    'Dharmapuri',
    'Ariyalur',
    'Perambalur',
    'Kallakurichi',
    'Mayiladuthurai',
    'Kanniyakumari'
  ],

  CLINICAL_DISCLAIMER: '⚠️ IMPORTANT MEDICAL DISCLAIMER: This AI Health Assistant provides preliminary triage, educational guidance, and specialist recommendations only. It is NOT a certified medical practitioner, diagnostic device, or substitute for professional clinical judgment. If you are experiencing an emergency, call 108/112 or visit the nearest emergency department immediately.',

  DEFAULT_DOCTORS: [
    {
      _id: 'doc_diya_1',
      user: { name: 'Dr. Diya Sharma', email: 'doctor.diya@hospital.com', mobile: '+91 9840100001' },
      specialization: 'Cardiologist',
      qualification: 'MBBS, MD (Cardiology), DM',
      hospital: 'Apollo Hospitals, Greams Road',
      district: 'Chennai',
      address: '21 Greams Lane, Thousand Lights, Chennai',
      consultationFee: 800,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.9,
      bio: 'Senior Consultant Interventional Cardiologist specializing in coronary angioplasty, heart failure, and preventive cardiac wellness.'
    },
    {
      _id: 'doc_katrina_2',
      user: { name: 'Dr. Katrina Fernandez', email: 'doctor.katrina@hospital.com', mobile: '+91 9840100002' },
      specialization: 'Dermatologist',
      qualification: 'MBBS, MD (DVL)',
      hospital: 'Ganga Medical Centre',
      district: 'Coimbatore',
      address: '313 Mettupalayam Road, Coimbatore',
      consultationFee: 650,
      availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:30 PM'],
      rating: 4.8,
      bio: 'Specialist in clinical dermatology, laser skin rejuvenation, pediatric dermatology, and chronic eczema management.'
    },
    {
      _id: 'doc_rayaan_3',
      user: { name: 'Dr. Rayaan Kapoor', email: 'doctor.rayaan@hospital.com', mobile: '+91 9840100003' },
      specialization: 'Neurologist',
      qualification: 'MBBS, MD, DM (Neurology)',
      hospital: 'Meenakshi Mission Hospital',
      district: 'Madurai',
      address: 'Melur Main Road, Lake Area, Madurai',
      consultationFee: 750,
      availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:00 AM', '03:00 PM', '05:00 PM'],
      rating: 4.9,
      bio: 'Expert in acute stroke interventions, Parkinson\'s management, neuromuscular disorders, and comprehensive epilepsy care.'
    },
    {
      _id: 'doc_riyana_4',
      user: { name: 'Dr. Riyana Sen', email: 'doctor.riyana@hospital.com', mobile: '+91 9840100004' },
      specialization: 'Pediatrician',
      qualification: 'MBBS, DCH, DNB (Pediatrics)',
      hospital: 'Manipal Childrens Clinic',
      district: 'Salem',
      address: 'Saradha College Road, Salem',
      consultationFee: 500,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:30 AM', '04:00 PM', '05:30 PM'],
      rating: 4.9,
      bio: 'Dedicated child healthcare specialist with extensive experience in neonatal intensive care, growth monitoring, and immunization.'
    },
    {
      _id: 'doc_adhira_5',
      user: { name: 'Dr. Adhira Nair', email: 'doctor.adhira@hospital.com', mobile: '+91 9840100005' },
      specialization: 'Orthopedic',
      qualification: 'MBBS, MS, M.Ch (Joint Replacement)',
      hospital: 'Kauvery Hospital',
      district: 'Tiruchirappalli',
      address: 'C-72, 6th Cross, Thillai Nagar, Trichy',
      consultationFee: 700,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
      rating: 4.8,
      bio: 'Consultant Orthopedic Surgeon specializing in robotic knee arthroplasty, complex trauma, and sports medicine rehabilitation.'
    },
    {
      _id: 'doc_ishita_6',
      user: { name: 'Dr. Ishita Patel', email: 'doctor.ishita@hospital.com', mobile: '+91 9840100006' },
      specialization: 'Gynecologist',
      qualification: 'MBBS, MS (OBG), FICOG',
      hospital: 'MIOT International',
      district: 'Chennai',
      address: '4/112 Mount Poonamallee Road, Manapakkam, Chennai',
      consultationFee: 750,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:30 AM', '03:30 PM', '05:00 PM'],
      rating: 4.9,
      bio: 'High-risk obstetrics specialist, laparoscopic gynecological surgeon, and fertility preservation counselor.'
    },
    {
      _id: 'doc_nethra_7',
      user: { name: 'Dr. Nethra Sundaram', email: 'doctor.nethra@hospital.com', mobile: '+91 9840100007' },
      specialization: 'General Physician',
      qualification: 'MBBS, MD (General Medicine)',
      hospital: 'CMC Hospital Care',
      district: 'Vellore',
      address: 'Ida Scudder Road, Vellore',
      consultationFee: 450,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM', '06:00 PM'],
      rating: 4.8,
      bio: 'Comprehensive internal medicine consultant specializing in chronic diabetes management, hypertension, and infectious diseases.'
    },
    {
      _id: 'doc_shaan_8',
      user: { name: 'Dr. Shaan Mukherjee', email: 'doctor.shaan@hospital.com', mobile: '+91 9840100008' },
      specialization: 'ENT Specialist',
      qualification: 'MBBS, MS (ENT), DLO',
      hospital: 'Shifa Health City',
      district: 'Tirunelveli',
      address: 'High Ground, Tirunelveli',
      consultationFee: 500,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.7,
      bio: 'Advanced micro-ear surgeon, endoscopic sinus surgery expert, and specialist in vertigo and pediatric ENT conditions.'
    },
    {
      _id: 'doc_roshini_9',
      user: { name: 'Dr. Roshini Krishnan', email: 'doctor.roshini@hospital.com', mobile: '+91 9840100009' },
      specialization: 'Pulmonologist',
      qualification: 'MBBS, MD (Pulmonary Med), FCCP',
      hospital: 'SIMS Hospital',
      district: 'Chennai',
      address: '1 Jawaharlal Nehru Salai, Vadapalani, Chennai',
      consultationFee: 750,
      availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
      rating: 4.8,
      bio: 'Consultant Pulmonologist with special interest in bronchial asthma, COPD, interstitial lung disease, and sleep apnea.'
    },
    {
      _id: 'doc_lavanya_10',
      user: { name: 'Dr. Lavanya Swaminathan', email: 'doctor.lavanya@hospital.com', mobile: '+91 9840100010' },
      specialization: 'Ophthalmologist',
      qualification: 'MBBS, MS (Ophthalmology), FICO',
      hospital: 'Lotus Eye Care Hospital',
      district: 'Erode',
      address: 'Perundurai Road, Erode',
      consultationFee: 550,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM'],
      rating: 4.9,
      bio: 'Phacoemulsification cataract surgeon, corneal specialist, laser vision correction clinician, and glaucoma care expert.'
    },
    {
      _id: 'doc_ishaan_11',
      user: { name: 'Dr. Ishaan Roy', email: 'doctor.ishaan@hospital.com', mobile: '+91 9840100011' },
      specialization: 'Psychiatrist',
      qualification: 'MBBS, MD (Psychiatry), DPM',
      hospital: 'VHS Hospital Health Campus',
      district: 'Chennai',
      address: 'Rajiv Gandhi Salai, Taramani, Chennai',
      consultationFee: 800,
      availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
      availableTimeSlots: ['11:00 AM', '02:00 PM', '04:00 PM', '06:00 PM'],
      rating: 4.9,
      bio: 'Compassionate mental health clinician specializing in mood stability, anxiety spectrum disorders, OCD, and psychotherapy.'
    },
    {
      _id: 'doc_aarav_12',
      user: { name: 'Dr. Aarav Mehta', email: 'doctor.aarav@hospital.com', mobile: '+91 9840100012' },
      specialization: 'Dentist',
      qualification: 'BDS, MDS (Oral Surgery)',
      hospital: 'Royal Dental Care',
      district: 'Coimbatore',
      address: 'Avinashi Road, Peelamedu, Coimbatore',
      consultationFee: 450,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '03:00 PM', '05:00 PM'],
      rating: 4.8,
      bio: 'Specialist in painless single-sitting root canal treatment, aesthetic cosmetic smile design, and dental implantology.'
    },
    {
      _id: 'doc_lishika_13',
      user: { name: 'Dr. Lishika Reddy', email: 'doctor.lishika@hospital.com', mobile: '+91 9840100013' },
      specialization: 'Gastroenterologist',
      qualification: 'MBBS, MD, DM (Gastroenterology)',
      hospital: 'Apollo Speciality Hospital',
      district: 'Madurai',
      address: 'KK Nagar, Madurai',
      consultationFee: 750,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:30 PM'],
      rating: 4.9,
      bio: 'Therapeutic GI endoscopist, liver disease specialist, inflammatory bowel disease consultant, and digestive health expert.'
    },
    {
      _id: 'doc_thanu_14',
      user: { name: 'Dr. Thanu Raghavan', email: 'doctor.thanu@hospital.com', mobile: '+91 9840100014' },
      specialization: 'Urologist',
      qualification: 'MBBS, MS, M.Ch (Urology)',
      hospital: 'Sri Gokulam Hospital',
      district: 'Salem',
      address: 'Meyyanur 3rd Cross, Salem',
      consultationFee: 650,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM'],
      rating: 4.8,
      bio: 'Endourology expert in laser kidney stone extraction (RIRS), holmium laser prostate surgery, and laparoscopic uro-oncology.'
    },
    {
      _id: 'doc_rajesh_15',
      user: { name: 'Dr. Rajesh Kumar', email: 'doctor.rajesh@hospital.com', mobile: '+91 9840100015' },
      specialization: 'Cardiologist',
      qualification: 'MBBS, MD (Cardiology), DM',
      hospital: 'Apollo Hospitals, Greams Road',
      district: 'Chennai',
      address: '21 Greams Lane, Thousand Lights, Chennai',
      consultationFee: 800,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.9,
      bio: 'Senior Consultant Interventional Cardiologist specializing in coronary angioplasty, heart failure, and preventive cardiac wellness.'
    },
    {
      _id: 'doc_ananya_16',
      user: { name: 'Dr. Ananya Sundaram', email: 'doctor.ananya@hospital.com', mobile: '+91 9840100016' },
      specialization: 'Dermatologist',
      qualification: 'MBBS, MD (Dermatology & Venereology)',
      hospital: 'Ganga Medical Centre',
      district: 'Coimbatore',
      address: '313 Mettupalayam Road, Coimbatore',
      consultationFee: 600,
      availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:30 PM'],
      rating: 4.8,
      bio: 'Specialist in clinical dermatology, laser skin therapies, psoriasis management, and pediatric skin conditions.'
    },
    {
      _id: 'doc_karthik_17',
      user: { name: 'Dr. Karthik Raman', email: 'doctor.karthik@hospital.com', mobile: '+91 9840100017' },
      specialization: 'Neurologist',
      qualification: 'MBBS, M.Ch (Neurosurgery)',
      hospital: 'Meenakshi Mission Hospital',
      district: 'Madurai',
      address: 'Melur Main Road, Lake Area, Madurai',
      consultationFee: 750,
      availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:00 AM', '03:00 PM', '05:00 PM'],
      rating: 4.9,
      bio: 'Expert in cerebrovascular disorders, stroke rehabilitation, epilepsy management, and neuromuscular diseases.'
    },
    {
      _id: 'doc_priya_18',
      user: { name: 'Dr. Priya Venkatesh', email: 'doctor.priya@hospital.com', mobile: '+91 9840100018' },
      specialization: 'Pediatrician',
      qualification: 'MBBS, DCH, DNB (Pediatrics)',
      hospital: 'Manipal Childrens Clinic',
      district: 'Salem',
      address: 'Saradha College Road, Salem',
      consultationFee: 500,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['09:00 AM', '10:30 AM', '04:00 PM', '05:30 PM'],
      rating: 4.9,
      bio: 'Dedicated child healthcare specialist with extensive experience in neonatal care, growth monitoring, and immunization.'
    },
    {
      _id: 'doc_vijay_19',
      user: { name: 'Dr. Vijay Raghavan', email: 'doctor.vijay@hospital.com', mobile: '+91 9840100019' },
      specialization: 'Orthopedic',
      qualification: 'MBBS, MS (Orthopedics)',
      hospital: 'Kauvery Hospital',
      district: 'Tiruchirappalli',
      address: 'C-72, 6th Cross, Thillai Nagar, Trichy',
      consultationFee: 650,
      availableDays: ['Monday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '02:00 PM', '04:00 PM'],
      rating: 4.8,
      bio: 'Specialist in joint replacement surgery, arthroscopic knee reconstruction, and spinal rehabilitation.'
    },
    {
      _id: 'doc_meena_20',
      user: { name: 'Dr. Meena Krishnan', email: 'doctor.meena@hospital.com', mobile: '+91 9840100020' },
      specialization: 'ENT Specialist',
      qualification: 'MBBS, MS (ENT), DLO',
      hospital: 'Shifa Health City',
      district: 'Tirunelveli',
      address: 'High Ground, Tirunelveli',
      consultationFee: 500,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '03:00 PM', '04:00 PM'],
      rating: 4.7,
      bio: 'Advanced micro-ear surgery specialist, endoscopic sinus surgeon, and vertigo diagnosis expert.'
    },
    {
      _id: 'doc_suresh_21',
      user: { name: 'Dr. Suresh Kumar', email: 'doctor.suresh@hospital.com', mobile: '+91 9840100021' },
      specialization: 'General Physician',
      qualification: 'MBBS, MD (General Medicine)',
      hospital: 'CMC Hospital Care',
      district: 'Vellore',
      address: 'Ida Scudder Road, Vellore',
      consultationFee: 400,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM', '06:00 PM'],
      rating: 4.8,
      bio: 'Comprehensive internal medicine consultant specializing in chronic diabetes management, hypertension, and fever triage.'
    },
    {
      _id: 'doc_sneha_22',
      user: { name: 'Dr. Sneha Parthasarathy', email: 'doctor.sneha@hospital.com', mobile: '+91 9840100022' },
      specialization: 'Gynecologist',
      qualification: 'MBBS, MS (OBG), FICOG',
      hospital: 'MIOT International',
      district: 'Chennai',
      address: '4/112 Mount Poonamallee Road, Manapakkam, Chennai',
      consultationFee: 700,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:30 AM', '03:30 PM', '05:00 PM'],
      rating: 4.9,
      bio: 'High-risk obstetrics specialist, laparoscopic gynecological surgeon, and fertility preservation counselor.'
    },
    {
      _id: 'doc_anand_23',
      user: { name: 'Dr. Anand Chandrasekar', email: 'doctor.anand@hospital.com', mobile: '+91 9840100023' },
      specialization: 'Pulmonologist',
      qualification: 'MBBS, MD (Pulmonary Medicine), FCCP',
      hospital: 'SIMS Hospital',
      district: 'Chennai',
      address: '1 Jawaharlal Nehru Salai, Vadapalani, Chennai',
      consultationFee: 750,
      availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
      rating: 4.8,
      bio: 'Consultant Pulmonologist with special interest in asthma, COPD, sleep apnea, and post-viral pulmonary rehabilitation.'
    },
    {
      _id: 'doc_divya_24',
      user: { name: 'Dr. Divya Balaji', email: 'doctor.divya@hospital.com', mobile: '+91 9840100024' },
      specialization: 'Ophthalmologist',
      qualification: 'MBBS, MS (Ophthalmology)',
      hospital: 'Lotus Eye Care Hospital',
      district: 'Erode',
      address: 'Perundurai Road, Erode',
      consultationFee: 550,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '03:30 PM'],
      rating: 4.9,
      bio: 'Phacoemulsification cataract surgeon, corneal specialist, and laser vision correction clinician.'
    },
    {
      _id: 'doc_sanjay_25',
      user: { name: 'Dr. Sanjay Mohan', email: 'doctor.sanjay@hospital.com', mobile: '+91 9840100025' },
      specialization: 'Psychiatrist',
      qualification: 'MBBS, MD (Psychiatry)',
      hospital: 'VHS Hospital Health Campus',
      district: 'Chennai',
      address: 'Rajiv Gandhi Salai, Taramani, Chennai',
      consultationFee: 800,
      availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
      availableTimeSlots: ['11:00 AM', '02:00 PM', '04:00 PM', '06:00 PM'],
      rating: 4.9,
      bio: 'Compassionate mental health clinician specializing in mood stability, anxiety spectrum disorders, and psychotherapy.'
    },
    {
      _id: 'doc_kavitha_26',
      user: { name: 'Dr. Kavitha Rajan', email: 'doctor.kavitha@hospital.com', mobile: '+91 9840100026' },
      specialization: 'Dentist',
      qualification: 'BDS, MDS (Conservative Dentistry & Endodontics)',
      hospital: 'Royal Dental & Maxillofacial Care',
      district: 'Coimbatore',
      address: 'Avinashi Road, Peelamedu, Coimbatore',
      consultationFee: 400,
      availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:00 AM', '03:00 PM', '05:00 PM'],
      rating: 4.8,
      bio: 'Painless single-sitting root canal specialist, aesthetic cosmetic dentistry, and dental implantology.'
    },
    {
      _id: 'doc_ramesh_27',
      user: { name: 'Dr. Ramesh Babu', email: 'doctor.ramesh@hospital.com', mobile: '+91 9840100027' },
      specialization: 'Gastroenterologist',
      qualification: 'MBBS, MD, DM (Gastroenterology)',
      hospital: 'Apollo Speciality Hospital',
      district: 'Madurai',
      address: 'KK Nagar, Madurai',
      consultationFee: 700,
      availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
      availableTimeSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:30 PM'],
      rating: 4.9,
      bio: 'Therapeutic GI endoscopist, liver disease specialist, and inflammatory bowel disease consultant.'
    },
    {
      _id: 'doc_swetha_28',
      user: { name: 'Dr. Swetha Subramanian', email: 'doctor.swetha@hospital.com', mobile: '+91 9840100028' },
      specialization: 'Urologist',
      qualification: 'MBBS, MS, M.Ch (Urology)',
      hospital: 'Sri Gokulam Hospital',
      district: 'Salem',
      address: 'Meyyanur 3rd Cross, Salem',
      consultationFee: 650,
      availableDays: ['Tuesday', 'Thursday', 'Saturday'],
      availableTimeSlots: ['10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM'],
      rating: 4.8,
      bio: 'Endourology expert in laser kidney stone extraction, prostate management, and laparoscopic urology.'
    }
  ]
};
